-- Admin bootstrap instructions
--
-- 1. Create the administrator through Supabase Authentication using a unique,
--    strong password. Never create auth.users rows manually and never commit
--    passwords or recovery credentials to this repository.
-- 2. Copy the new user's UUID from Authentication > Users.
-- 3. In the Supabase SQL editor, run the parameterized statement below after
--    replacing ADMIN_USER_UUID. Do not commit the populated value.
--
-- insert into public.admin_users (user_id, email, role)
-- select id, email, 'admin'
-- from auth.users
-- where id = 'ADMIN_USER_UUID'::uuid
-- on conflict (user_id) do update
-- set email = excluded.email,
--     role = 'admin';
--
-- The harden_admin_access migration makes this table server-controlled and
-- allows an authenticated administrator to read only their own membership.
